obstacle_range: 2.5
raytrace_range: 3.0
footprint: [[0.38, 0.38], [-0.38, 0.38],[-0.38, -0.38], [0.38, -0.38]]
#robot_radius: 0.3

static_layer:
 map_toic: map
 subsribe_to_updates: true

obstacle_layer:
 observation_sources: laser_scan_sensor 

 laser_scan_sensor: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true}

inflation_layer:
 inflation_radius: 0.2
 cost_scaling_factor: 3